server:
  port: 8211

spring:
  application:
    name: user
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/