server:
  port: 8212

spring:
  application:
    name: user

  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server

  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/