server:
  port: 8888

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youyud/YouyuCloudConfig.git
      label: master
